# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a2sOp7rNjfZm13tjJ57f2L788ve2fSP
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

new = pd.read_csv("//content/book1.csv")

X = new[['weight(x2)','Height(y2)']].values
Y = new['class'].values

#training, testing
X_train, X_test, Y_train , Y_test = train_test_split(X,Y, test_size=0.2,random_state=42)

#KNN
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train,Y_train)

new = np.array([[57,170]])

Y_pred = knn.predict(new)



print(Y_pred)
print(new)